resolver: lts-14.23

flags:
  byline:
    maintainer: true
    build-examples: true

packages:
  - ./

nix:
  enable: false
  shell-file: stack.nix

extra-deps:
  - terminfo-hs-0.2.1
  - ansi-terminal-0.8.2
